### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by NinjaCross** [amoerie/keyed-semaphores#14]
This seems to be a very interesting project, kudos !
I was wondering (well, my customers are) which are the performances of this implementation.
Do you have any benchmark ?
Thanks.

**Comment by amoerie** [comment]
Sure why not. As a baseline, I would compare this library to maintaining your own dictionary of SemaphoreSlim instances. This benchmark will reveal the "overhead" of using this library. 

I've written two benchmarks, one with a dictionary of SemaphoreSlim and one that uses KeyedSemaphore.LockAsync.
For completeness, it should be noted that a KeyedSemaphoreCollection will keep track of its consumers and automatically remove unused keys after the last usage automatically. My quickly hand-rolled dictionary of SemaphoreSlim does not keep track of the number of consumers per key and therefore also does not do any cleanup.

```csharp
using System.Collections.Concurrent;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using KeyedSemaphores;

BenchmarkRunner.Run<KeyedSemaphoreBenchmarks>();

[MemoryDiagnoser]
public class KeyedSemaphoreBenchmarks
{
    [Params(1, 10, 100)] 
    public int NumberOfLocks { get; set; }

    [Params(1, 10, 100)] 
    public int Contention { get; set; }

    [Benchmark(Baseline = true)]
    public async Task DictionaryOfSemaphoreSlims()
    {
        var semaphores = new ConcurrentDictionary<string, SemaphoreSlim>(Environment.ProcessorCount, NumberOfLocks);
        var tasks = Enumerable.Range(0, Contention * NumberOfLocks).Select(async i =>
        {
            string key = i.ToString();
            SemaphoreSlim? semaphore;
            
            // get or create a semaphore
            while (true)
            {
                if (semaphores.TryGetValue(key, out semaphore))
                    break;

                semaphore = new SemaphoreSlim(1, 1);

                if (semaphores.TryAdd(key, semaphore))
                    break;
                
                semaphore.Dispose();
            }

            await semaphore.WaitAsync();
            try
            {
                await Task.Delay(1);
            }
            finally
            {
                semaphore.Release();
            }

            return Task.CompletedTask;
        });

        await Task.WhenAll(tasks);
    }

    [Benchmark]
    public async Task KeyedSemaphores()
    {
        var tasks = Enumerable.Range(0, Contention * NumberOfLocks).Select(async i =>
        {
            string key = i.ToString();

            using var _ = await KeyedSemaphore.LockAsync(key);
            
            await Task.Delay(1);
        });

        await Task.WhenAll(tasks);
    }
}
```

I get the following results:

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22621
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.300
  [Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
  DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT


```
|                     Method | NumberOfLocks | Contention |     Mean |    Error |   StdDev | Ratio | RatioSD |     Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|--------------------------- |-------------- |----------- |---------:|---------:|---------:|------:|--------:|----------:|---------:|---------:|----------:|
| **DictionaryOfSemaphoreSlims** |             **1** |          **1** | **15.67 ms** | **0.139 ms** | **0.123 ms** |  **1.00** |    **0.00** |         **-** |        **-** |        **-** |      **2 KB** |
|            KeyedSemaphores |             1 |          1 | 15.66 ms | 0.242 ms | 0.227 ms |  1.00 |    0.02 |         - |        - |        - |      1 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |             **1** |         **10** | **15.55 ms** | **0.051 ms** | **0.045 ms** |  **1.00** |    **0.00** |         **-** |        **-** |        **-** |      **8 KB** |
|            KeyedSemaphores |             1 |         10 | 15.55 ms | 0.210 ms | 0.196 ms |  1.00 |    0.01 |         - |        - |        - |      9 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |             **1** |        **100** | **15.64 ms** | **0.299 ms** | **0.280 ms** |  **1.00** |    **0.00** |         **-** |        **-** |        **-** |     **60 KB** |
|            KeyedSemaphores |             1 |        100 | 15.69 ms | 0.242 ms | 0.227 ms |  1.00 |    0.02 |         - |        - |        - |     88 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |            **10** |          **1** | **15.54 ms** | **0.061 ms** | **0.051 ms** |  **1.00** |    **0.00** |         **-** |        **-** |        **-** |      **7 KB** |
|            KeyedSemaphores |            10 |          1 | 15.61 ms | 0.144 ms | 0.135 ms |  1.00 |    0.01 |         - |        - |        - |      9 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |            **10** |         **10** | **15.68 ms** | **0.246 ms** | **0.230 ms** |  **1.00** |    **0.00** |         **-** |        **-** |        **-** |     **59 KB** |
|            KeyedSemaphores |            10 |         10 | 15.69 ms | 0.258 ms | 0.229 ms |  1.00 |    0.02 |         - |        - |        - |     88 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |            **10** |        **100** | **16.80 ms** | **0.336 ms** | **0.867 ms** |  **1.00** |    **0.00** |   **93.7500** |  **31.2500** |        **-** |    **591 KB** |
|            KeyedSemaphores |            10 |        100 | 16.68 ms | 0.331 ms | 0.935 ms |  1.00 |    0.08 |  125.0000 |  62.5000 |        - |    876 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |           **100** |          **1** | **15.63 ms** | **0.162 ms** | **0.144 ms** |  **1.00** |    **0.00** |         **-** |        **-** |        **-** |     **54 KB** |
|            KeyedSemaphores |           100 |          1 | 15.59 ms | 0.180 ms | 0.159 ms |  1.00 |    0.01 |         - |        - |        - |     88 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |           **100** |         **10** | **16.71 ms** | **0.334 ms** | **0.857 ms** |  **1.00** |    **0.00** |   **62.5000** |  **31.2500** |        **-** |    **565 KB** |
|            KeyedSemaphores |           100 |         10 | 16.77 ms | 0.330 ms | 0.578 ms |  1.01 |    0.06 |  140.6250 |  62.5000 |        - |    876 KB |
|                            |               |            |          |          |          |       |         |           |          |          |           |
| **DictionaryOfSemaphoreSlims** |           **100** |        **100** | **21.45 ms** | **0.748 ms** | **2.205 ms** |  **1.00** |    **0.00** |  **937.5000** | **437.5000** | **156.2500** |  **5,715 KB** |
|            KeyedSemaphores |           100 |        100 | 23.02 ms | 0.668 ms | 1.970 ms |  1.08 |    0.13 | 1406.2500 | 562.5000 | 281.2500 |  8,850 KB |

My preliminary conclusion:

This library adds very little overhead in terms of CPU or RAM usage over handwriting your own dictionary of SemaphoreSlim instances. 
Feel free to argue with the implementation of the benchmark, this was written in a *very* short time...

**Comment by NinjaCross** [comment]
Thankyou very much, this is indeed very usefull !
