### ISSUE TITLE
Non-static implementation

### ISSUE THREAD

**Issue by NinjaCross** [amoerie/keyed-semaphores#16]
This request is related to #15 
In #15 i mentioned the fact that I often have the need to use non-string keys, such as Int32, Int64, or Guid keys (usually PKs or "surrogate PKs" of a table in a database).
Let's say that I need to semaphorize the access to a record of a **specific** database table given its Int32/In64 "ID" column.
When using an (hypotetical and generic) implementation of this Semaphore having a Int32 (generic `<T>`) key, the identity of a lock cannot be considered "universal/global" given a certain Int32, since multiple tables contains records having the same Int32 number as ID field.
This means that I need to create a per-table repository, and I cannot use the current implementation like this:

```cs
public class BankTransactionProcessor
{
  public async Task Process(BankTransaction transaction) 
  {
    var key = transaction.Person.Id.ToString();
    using (await KeyedSemaphore.LockAsync(key))
    {
      ...
    }
  }
}
```

I need something like this (which would work, even if it's a bit "ugly"):

```cs

public class BankTransaction 
{
public PersonsTable Person {get;set;}
}

public class PersonsTable
{
  public static readonly KeyedSemaphoreCollection<Int32> TableIdsSemaphores = new KeyedSemaphoresCollection<Int32>();
}

public class BankTransactionProcessor
{
  public async Task Process(BankTransaction transaction) 
  {
    // here I specify the collection of semaphores to use, and a Int32 key
    using (await KeyedSemaphore.LockAsync(PersonsTable.TableIdsSemaphores,  transaction.Person.Id))
    {
      ...
    }
  }
}
```

An even better use case would be something like this:

```cs

public class BankTransaction 
{
public PersonsTable Person {get;set;}
}

public class PersonsTable
{
  public static readonly KeyedSemaphoreCollection<Int32> TableIdsSemaphores = new KeyedSemaphoresCollection<Int32>();
}

public class BankTransactionProcessor
{
  public async Task Process(BankTransaction transaction) 
  {
    // here I specify the collection of semaphores to use, and a Int32 key
    using (await PersonsTable.TableIdsSemaphores.LockAsync(transaction.Person.Id))
    {
      ...
    }
  }
}
```

**Comment by amoerie** [comment]
In our applications we typically solve this by just prefixing the keys with a certain text, but I agree that this is less optimal, not only for code maintenance but also performance wise. (having to search through a large index will take longer)

Can you give 2.2.0 a try? I've made the `KeyedSemaphoresCollection` constructor public and documented its public APIs.
`Lock(Async)` is defined as an extension method too.

**Comment by NinjaCross** [comment]
Thankyou, I will give it a spin today :)

**Comment by amoerie** [comment]
Since the non static API is now released, I'll close this issue. Feel free to make a new one if you still have questions or problems. 👍
