### ISSUE TITLE
Missed method is it locked

### ISSUE THREAD

**Issue by knopa** [amoerie/keyed-semaphores#44]
Thanks for nice library

I think it defenetly miss a method which allow to check if key already locked without locking it.
with usual semaphore it possible with CurrentCount checking

**Comment by knopa** [comment]
Some kind of **.Contains(key)**
which would allow me to skip lock part for example

for PR I will try to add but not promissing

**Comment by knopa** [comment]
I have created PR
https://github.com/amoerie/keyed-semaphores/pull/45
not sure if test are good

**Comment by amoerie** [comment]
Included in 3.2.0

@knopa thanks a lot for contributing! 🥳
